[project]
name        = "smartdirs"
description = "📂 System Directories and Utilities"
version     = "0.0.2"
license     = "MIT"
readme      = "readme.md"
requires-python = ">=3.10"
dependencies = [
    "pydantic",
]

[project.urls]
GitHub = "https://github.com/BrokenSource/SmartDirs"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
